### ISSUE TITLE
Create and use service account 

### ISSUE THREAD

**Issue by sblack4** [TonicAI/tonic_helm_charts#17]
I'd like to deploy this in EKS and use an [IAM role via a service account](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

Your docs specify this permissions which I think needs assumed by the worker node. 
https://docs.tonic.ai/app/setting-up-your-database/snowflake/initial-tonic-setup#aws-instance-profile-permissions

**Comment by akamor** [comment]
@sblack4 I'm not super familiar with your specific setup.  Is there something we need to change on our end?

**Comment by sblack4** [comment]
Yeah, most helm charts I've worked with create a service account and then attach it to the resources. Here's an example I'm familiar with [where a chart optionally creates a SA](https://github.com/KongZ/charts/blob/main/charts/graylog/templates/serviceaccount.yaml) and [attaches it to a resource](https://github.com/KongZ/charts/blob/main/charts/graylog/templates/statefulset.yaml#L30)
