### ISSUE TITLE
Allow for env vars in worker node 

### ISSUE THREAD

**Issue by sblack4** [TonicAI/tonic_helm_charts#18]
The lambda role and ECR name are configured via env vars. It would be nice to pass them in via the chart

- docs for lambda role and ecr name https://docs.tonic.ai/app/setting-up-your-database/snowflake/initial-tonic-setup#aws-lambda-role
- see the `env` and `envRaw` here for an example https://github.com/KongZ/charts/blob/main/charts/graylog/templates/statefulset.yaml#L127

**Comment by akamor** [comment]
@sblack4 Good catch, thanks.  We can make that change for the lambda role.  The ECR name has an actual default value in our code of tonic_lambda so the variable itself need not actually be set unless you plan on overriding.

**Comment by sblack4** [comment]
Thanks, it's be ideal to specify it ourselves. What's the default value?

**Comment by akamor** [comment]
tonic_lambda

**Comment by sblack4** [comment]
This should be as easy as adding 
```
            {{- range $key, $value := .Values.tonicai.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.tonicai.envRaw }}
            {{- with .Values.tonicai.envRaw }}
                {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
```

to the deployment,  https://github.com/TonicAI/tonic_helm_charts/blob/master/templates/tonic-worker-deployment.yaml
